---
- name: Jenkins Master Installation by Ansible
  hosts: localhost
  vars_files:
    - jenkins-master_vars.yaml

  tasks:

  - name: Jenkins Master Installation Tasks - Base
    include_tasks: jenkins-master_tasks-base.yaml

  - name: Jenkins Master Installation Tasks - Extra
    include_tasks: jenkins-master_tasks-extra.yaml

  - name: Jenkins Master Installation Tasks - Projects
    include_tasks: jenkins-master_tasks-projects.yaml
