
- name: jenkins-master2
  hosts: all
  become: true

  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-1.8.0-openjdk-devel
    jenkins_plugins:
      - blueocean

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
